In [1]:
import numpy as np
import matplotlib.pyplot as plt  # To visualize
import pandas as pd  # To read data
from sklearn.linear_model import LinearRegression

In [2]:
seasons= [2011,2012,2013,2014,2015,2016,2017,2018,2019,2021,2022]

In [3]:
df = pd.DataFrame()

In [4]:

for season in seasons:
    
    new_df = pd.read_csv(f'./data/{season}_season.csv')
    new_df['Season'] = season
    new_df = new_df[new_df.Tm != "Average"]
    #new_df.drop('Luck▼', inplace=True)
    #new_df.drop('W-L%▼', inplace=True)
    
    
    df = pd.concat([df, new_df], ignore_index=True)

In [5]:
df

,Rk,Tm,W,L,W-L%,R,RA,Rdiff,SOS,SRS,...,vLHP,≥.500,<.500,Season,Luck▼,W-L%▼,Strk,last10,last20,last30
0,1.0,Philadelphia Phillies,102,60,0.630,4.4,3.3,1.1,-0.1,1.0,...,30-14,37-25,65-35,2011,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,New York Yankees,97,65,0.599,5.4,4.1,1.3,0.1,1.4,...,35-17,44-38,53-27,2011,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Texas Rangers,96,66,0.593,5.3,4.2,1.1,0.1,1.2,...,26-21,35-37,61-29,2011,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Milwaukee Brewers,96,66,0.593,4.5,3.9,0.5,-0.2,0.3,...,18-18,27-34,69-32,2011,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Detroit Tigers,95,67,0.586,4.9,4.4,0.5,-0.1,0.4,...,31-20,28-23,67-44,2011,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,26.0,Kansas City Royals,65,97,0.401,4.0,5.0,-1.0,0.1,-1.0,...,20-21,34-58,31-39,2022,NaN,NaN,L 2,3-7,8-12,12-18
326,27.0,Pittsburgh Pirates,62,100,0.383,3.6,5.0,-1.4,0.0,-1.4,...,22-33,26-64,36-36,2022,NaN,NaN,W 1,6-4,8-12,13-17
327,28.0,Cincinnati Reds,62,100,0.383,4.0,5.0,-1.0,-0.1,-1.1,...,17-29,32-61,30-39,2022,NaN,NaN,L 1,3-7,6-14,9-21
328,29.0,Oakland Athletics,60,102,0.370,3.5,4.8,-1.2,0.2,-1.0,...,16-27,33-60,27-42,2022,NaN,NaN,W 4,4-6,9-11,11-19
329,30.0,Washington Nationals,55,107,0.340,3.7,5.3,-1.6,0.1,-1.4,...,16-40,30-70,25-37,2022,NaN,NaN,L 5,2-8,6-14,10-20

In [6]:
df.dropna(axis='columns', inplace=True)

In [7]:
df['win%']= df['W']/162

In [8]:
df

,Rk,Tm,W,L,R,RA,Rdiff,SOS,SRS,pythWL,...,Home,Road,ExInn,1Run,vRHP,vLHP,≥.500,<.500,Season,win%
0,1.0,Philadelphia Phillies,102,60,4.4,3.3,1.1,-0.1,1.0,103-59,...,52-29,50-31,9-10,28-19,72-46,30-14,37-25,65-35,2011,0.629630
1,2.0,New York Yankees,97,65,5.4,4.1,1.3,0.1,1.4,101-61,...,52-29,45-36,4-12,21-24,62-48,35-17,44-38,53-27,2011,0.598765
2,3.0,Texas Rangers,96,66,5.3,4.2,1.1,0.1,1.2,98-64,...,52-29,44-37,4-5,19-24,70-45,26-21,35-37,61-29,2011,0.592593
3,4.0,Milwaukee Brewers,96,66,4.5,3.9,0.5,-0.2,0.3,90-72,...,57-24,39-42,7-7,30-18,78-48,18-18,27-34,69-32,2011,0.592593
4,5.0,Detroit Tigers,95,67,4.9,4.4,0.5,-0.1,0.4,89-73,...,50-31,45-36,6-3,29-17,64-47,31-20,28-23,67-44,2011,0.586420
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,26.0,Kansas City Royals,65,97,4.0,5.0,-1.0,0.1,-1.0,64-98,...,39-42,26-55,5-5,16-20,45-76,20-21,34-58,31-39,2022,0.401235
326,27.0,Pittsburgh Pirates,62,100,3.6,5.0,-1.4,0.0,-1.4,58-104,...,34-47,28-53,4-9,21-27,40-67,22-33,26-64,36-36,2022,0.382716
327,28.0,Cincinnati Reds,62,100,4.0,5.0,-1.0,-0.1,-1.1,64-98,...,33-48,29-52,6-5,21-23,45-71,17-29,32-61,30-39,2022,0.382716
328,29.0,Oakland Athletics,60,102,3.5,4.8,-1.2,0.2,-1.0,59-103,...,29-51,31-51,6-4,17-25,44-75,16-27,33-60,27-42,2022,0.370370
329,30.0,Washington Nationals,55,107,3.7,5.3,-1.6,0.1,-1.4,56-106,...,26-55,29-52,3-7,17-22,39-67,16-40,30-70,25-37,2022,0.339506

In [9]:
df.columns

Index(['Rk', 'Tm', 'W', 'L', 'R', 'RA', 'Rdiff', 'SOS', 'SRS', 'pythWL',
       'vEast', 'vCent', 'vWest', 'Inter', 'Home', 'Road', 'ExInn', '1Run',
       'vRHP', 'vLHP', '≥.500', '<.500', 'Season', 'win%'],
      dtype='object')

In [10]:
df['pythW % **2'] = (df['R']**2)/(df['R']**2+df['RA']**2)

In [11]:
df[df['pythW % **2']== df['pythW % **2'].min()]['pythW % **2']

261    0.285149
Name: pythW % **2, dtype: float64

In [12]:
df['pythW % **3'] = (df['R']**3)/(df['R']**3+df['RA']**3)

In [13]:
df['pythW % **3']

0      0.703297
1      0.695558
2      0.667715
3      0.605707
4      0.580029
         ...
325    0.338624
326    0.271799
327    0.338624
328    0.279376
329    0.253862
Name: pythW % **3, Length: 330, dtype: float64

In [14]:
val_list =np.arange(0.0,5.0,.1)

In [15]:
val_list=np.round(val_list,2).tolist()

In [16]:
for i in val_list:
    df[f'pytW %_{i}']= (df['R']**i)/(df['R']**i+df['RA']**i)
    #df[f'pytW %_{i}_diff']=df[f'pytW %_{i}'] - df['win%']

In [17]:
df

,Rk,Tm,W,L,R,RA,Rdiff,SOS,SRS,pythWL,...,pytW %_4.0,pytW %_4.1,pytW %_4.2,pytW %_4.3,pytW %_4.4,pytW %_4.5,pytW %_4.6,pytW %_4.7,pytW %_4.8,pytW %_4.9
0,1.0,Philadelphia Phillies,102,60,4.4,3.3,1.1,-0.1,1.0,103-59,...,0.759644,0.764857,0.769992,0.775047,0.780023,0.784920,0.789736,0.794474,0.799131,0.803709
1,2.0,New York Yankees,97,65,5.4,4.1,1.3,0.1,1.4,101-61,...,0.750569,0.755689,0.760738,0.765715,0.770620,0.775452,0.780211,0.784897,0.789511,0.794051
2,3.0,Texas Rangers,96,66,5.3,4.2,1.1,0.1,1.2,98-64,...,0.717175,0.721869,0.726515,0.731113,0.735661,0.740160,0.744609,0.749007,0.753355,0.757652
3,4.0,Milwaukee Brewers,96,66,4.5,3.9,0.5,-0.2,0.3,90-72,...,0.639318,0.642611,0.645890,0.649157,0.652409,0.655647,0.658870,0.662079,0.665273,0.668452
4,5.0,Detroit Tigers,95,67,4.9,4.4,0.5,-0.1,0.4,89-73,...,0.605998,0.608565,0.611126,0.613681,0.616230,0.618772,0.621307,0.623836,0.626359,0.628874
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,26.0,Kansas City Royals,65,97,4.0,5.0,-1.0,0.1,-1.0,64-98,...,0.290579,0.286001,0.281466,0.276975,0.272529,0.268127,0.263771,0.259460,0.255196,0.250978
326,27.0,Pittsburgh Pirates,62,100,3.6,5.0,-1.4,0.0,-1.4,58-104,...,0.211816,0.206383,0.201054,0.195829,0.190708,0.185689,0.180773,0.175959,0.171246,0.166634
327,28.0,Cincinnati Reds,62,100,4.0,5.0,-1.0,-0.1,-1.1,64-98,...,0.290579,0.286001,0.281466,0.276975,0.272529,0.268127,0.263771,0.259460,0.255196,0.250978
328,29.0,Oakland Athletics,60,102,3.5,4.8,-1.2,0.2,-1.0,59-103,...,0.220387,0.215008,0.209725,0.204538,0.199447,0.194452,0.189552,0.184747,0.180037,0.175422
329,30.0,Washington Nationals,55,107,3.7,5.3,-1.6,0.1,-1.4,56-106,...,0.191933,0.186421,0.181032,0.175765,0.170619,0.165594,0.160688,0.155900,0.151229,0.146674

In [18]:
df2=pd.DataFrame()
df3=pd.DataFrame()

In [20]:
df[f'pytW %_4.7_diff'].mean()

KeyError: 'pytW %_4.7_diff'

In [32]:
for i in val_list:
    df2[f'pytW %_{i}_mean']=df[f'pytW %_{i}_diff'].mean()
    df2[f'pytW %_{i}_median']=df[f'pytW %_{i}_diff'].median()

In [33]:
df2

Empty DataFrame
Columns: [pytW %_0.0_mean, pytW %_0.0_median, pytW %_0.1_mean, pytW %_0.1_median, pytW %_0.2_mean, pytW %_0.2_median, pytW %_0.3_mean, pytW %_0.3_median, pytW %_0.4_mean, pytW %_0.4_median, pytW %_0.5_mean, pytW %_0.5_median, pytW %_0.6_mean, pytW %_0.6_median, pytW %_0.7_mean, pytW %_0.7_median, pytW %_0.8_mean, pytW %_0.8_median, pytW %_0.9_mean, pytW %_0.9_median, pytW %_1.0_mean, pytW %_1.0_median, pytW %_1.1_mean, pytW %_1.1_median, pytW %_1.2_mean, pytW %_1.2_median, pytW %_1.3_mean, pytW %_1.3_median, pytW %_1.4_mean, pytW %_1.4_median, pytW %_1.5_mean, pytW %_1.5_median, pytW %_1.6_mean, pytW %_1.6_median, pytW %_1.7_mean, pytW %_1.7_median, pytW %_1.8_mean, pytW %_1.8_median, pytW %_1.9_mean, pytW %_1.9_median, pytW %_2.0_mean, pytW %_2.0_median, pytW %_2.1_mean, pytW %_2.1_median, pytW %_2.2_mean, pytW %_2.2_median, pytW %_2.3_mean, pytW %_2.3_median, pytW %_2.4_mean, pytW %_2.4_median, pytW %_2.5_mean, pytW %_2.5_median, pytW %_2.6_mean, pytW %_2.6_median, pytW %_2.7_mean, pytW %_2.7_median, pytW %_2.8_mean, pytW %_2.8_median, pytW %_2.9_mean, pytW %_2.9_median, pytW %_3.0_mean, pytW %_3.0_median, pytW %_3.1_mean, pytW %_3.1_median, pytW %_3.2_mean, pytW %_3.2_median, pytW %_3.3_mean, pytW %_3.3_median, pytW %_3.4_mean, pytW %_3.4_median, pytW %_3.5_mean, pytW %_3.5_median, pytW %_3.6_mean, pytW %_3.6_median, pytW %_3.7_mean, pytW %_3.7_median, pytW %_3.8_mean, pytW %_3.8_median, pytW %_3.9_mean, pytW %_3.9_median, pytW %_4.0_mean, pytW %_4.0_median, pytW %_4.1_mean, pytW %_4.1_median, pytW %_4.2_mean, pytW %_4.2_median, pytW %_4.3_mean, pytW %_4.3_median, pytW %_4.4_mean, pytW %_4.4_median, pytW %_4.5_mean, pytW %_4.5_median, pytW %_4.6_mean, pytW %_4.6_median, pytW %_4.7_mean, pytW %_4.7_median, pytW %_4.8_mean, pytW %_4.8_median, pytW %_4.9_mean, pytW %_4.9_median]
Index: []

[0 rows x 100 columns]

In [21]:
df.columns

Index(['Rk', 'Tm', 'W', 'L', 'R', 'RA', 'Rdiff', 'SOS', 'SRS', 'pythWL',
       'vEast', 'vCent', 'vWest', 'Inter', 'Home', 'Road', 'ExInn', '1Run',
       'vRHP', 'vLHP', '≥.500', '<.500', 'Season', 'win%', 'pythW % **2',
       'pythW % **3', 'pytW %_0.0', 'pytW %_0.1', 'pytW %_0.2', 'pytW %_0.3',
       'pytW %_0.4', 'pytW %_0.5', 'pytW %_0.6', 'pytW %_0.7', 'pytW %_0.8',
       'pytW %_0.9', 'pytW %_1.0', 'pytW %_1.1', 'pytW %_1.2', 'pytW %_1.3',
       'pytW %_1.4', 'pytW %_1.5', 'pytW %_1.6', 'pytW %_1.7', 'pytW %_1.8',
       'pytW %_1.9', 'pytW %_2.0', 'pytW %_2.1', 'pytW %_2.2', 'pytW %_2.3',
       'pytW %_2.4', 'pytW %_2.5', 'pytW %_2.6', 'pytW %_2.7', 'pytW %_2.8',
       'pytW %_2.9', 'pytW %_3.0', 'pytW %_3.1', 'pytW %_3.2', 'pytW %_3.3',
       'pytW %_3.4', 'pytW %_3.5', 'pytW %_3.6', 'pytW %_3.7', 'pytW %_3.8',
       'pytW %_3.9', 'pytW %_4.0', 'pytW %_4.1', 'pytW %_4.2', 'pytW %_4.3',
       'pytW %_4.4', 'pytW %_4.5', 'pytW %_4.6', 'pytW %_4.7', 'pytW %_4.8',
       'pytW %_4.9'],
      dtype='object')

In [22]:
df2=df[df.columns[-100:]]

In [ ]:
X

In [59]:
df_=df2.describe().min()

In [60]:
df_

win%               0.077003
pytW %_0.0_diff   -0.185185
pytW %_0.1         0.004170
pytW %_0.1_diff   -0.173050
pytW %_0.2         0.008338
                     ...
pytW %_4.7_diff   -0.242855
pytW %_4.8         0.099235
pytW %_4.8_diff   -0.247546
pytW %_4.9         0.095202
pytW %_4.9_diff   -0.252151
Length: 100, dtype: float64

In [61]:
df2

,win%,pytW %_0.0_diff,pytW %_0.1,pytW %_0.1_diff,pytW %_0.2,pytW %_0.2_diff,pytW %_0.3,pytW %_0.3_diff,pytW %_0.4,pytW %_0.4_diff,...,pytW %_4.5,pytW %_4.5_diff,pytW %_4.6,pytW %_4.6_diff,pytW %_4.7,pytW %_4.7_diff,pytW %_4.8,pytW %_4.8_diff,pytW %_4.9,pytW %_4.9_diff
0,0.629630,-0.129630,0.507192,-0.122438,0.514380,-0.115249,0.521563,-0.108067,0.528737,-0.100893,...,0.784920,0.155290,0.789736,0.160107,0.794474,0.164844,0.799131,0.169502,0.803709,0.174080
1,0.598765,-0.098765,0.506885,-0.091881,0.513767,-0.084998,0.520644,-0.078121,0.527513,-0.071252,...,0.775452,0.176686,0.780211,0.181445,0.784897,0.186132,0.789511,0.190745,0.794051,0.195285
2,0.592593,-0.092593,0.505815,-0.086777,0.511629,-0.080964,0.517440,-0.075153,0.523245,-0.069347,...,0.740160,0.147567,0.744609,0.152016,0.749007,0.156415,0.753355,0.160763,0.757652,0.165059
3,0.592593,-0.092593,0.503577,-0.089015,0.507155,-0.085438,0.510731,-0.081862,0.514306,-0.078286,...,0.655647,0.063054,0.658870,0.066278,0.662079,0.069487,0.665273,0.072681,0.668452,0.075860
4,0.586420,-0.086420,0.502691,-0.083729,0.505381,-0.081038,0.508072,-0.078348,0.510761,-0.075658,...,0.618772,0.032352,0.621307,0.034888,0.623836,0.037417,0.626359,0.039939,0.628874,0.042454
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,0.401235,0.098765,0.494422,0.093187,0.488845,0.087610,0.483270,0.082036,0.477700,0.076466,...,0.268127,-0.133108,0.263771,-0.137464,0.259460,-0.141774,0.255196,-0.146039,0.250978,-0.150257
326,0.382716,0.117284,0.491788,0.109072,0.483581,0.100865,0.475382,0.092666,0.467197,0.084481,...,0.185689,-0.197027,0.180773,-0.201943,0.175959,-0.206757,0.171246,-0.211470,0.166634,-0.216082
327,0.382716,0.117284,0.494422,0.111706,0.488845,0.106129,0.483270,0.100554,0.477700,0.094984,...,0.268127,-0.114589,0.263771,-0.118945,0.259460,-0.123256,0.255196,-0.127520,0.250978,-0.131738
328,0.370370,0.129630,0.492104,0.121734,0.484213,0.113842,0.476329,0.105958,0.468457,0.098086,...,0.194452,-0.175918,0.189552,-0.180818,0.184747,-0.185623,0.180037,-0.190333,0.175422,-0.194949
329,0.339506,0.160494,0.491017,0.151510,0.482039,0.142533,0.473073,0.133567,0.464124,0.124618,...,0.165594,-0.173912,0.160688,-0.178819,0.155900,-0.183606,0.151229,-0.188277,0.146674,-0.192833